name: Update-UPM-Branch

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: "要建立 UPM branch 的既有版本 tag，例如 1.0.0。"
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag name
        id: tag
        run: echo "name=${{ github.event.inputs.git_tag }}" >> "$GITHUB_OUTPUT"

      - name: Create UPM Branches
        uses: hecomi/create-upm-branch-action@main
        with:
          git-tag: ${{ steps.tag.outputs.name }}
          pkg-root-dir-path: Packages/Ink
          samples-dir: Packages/Ink/Demos
